### ISSUE TITLE
[Crafting Tweaks and Resource Packs] Bug...?

### ISSUE THREAD

**Issue by Orc2000** [BedrockTweaks/Files#107]
**Pack or combination of packs which has the bug** 
Any combination, affects crafting tweaks AND resource packs

**Describe the bug**
Minecraft bedrock can only open .mcaddon and .mcpack files. However, when I download anything from the website, it is a .bin file, which minecraft cannot open and does not recognize

I do not think this is a bug, but I'd at least like to know the reasoning

**Screenshots**
I have none

**Device (please complete the following information):**
 - OS: Android 21, though I'm sure it happens on other devices too
 - Minecraft Version: 1.21.0

**Additional context**

**Comment by Goodlucksil** [comment]
Wow, Android 21.... Google is still on 15 or so....

**Comment by drav0011** [comment]
@Orc2000 Try using another browsers, there are issues in some android browsers which do not download mcpacks correctly

**Comment by NSPC911** [comment]
> there are issues in some android browsers which do not download mcpacks correctly

most do, just that opera gx doesnt
