### ISSUE TITLE
[CATEGORY] PACK Color Slimes

### ISSUE THREAD

**Issue by ParkR15MineR** [BedrockTweaks/Files#108]
**Pack or combination of packs which has the bug**

**Describe the bug**

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. iOS 16, Windows 11, Android 21, Xbox Series]
 - Minecraft Version: [e.g 1.21.0]

**Additional context**

**Comment by SquatchHunter** [comment]
@drav0011 close this one
