### ISSUE TITLE
[World of Color] Colored Slimes

### ISSUE THREAD

**Issue by ParkR15MineR** [BedrockTweaks/Files#109]
**Pack or combination of packs which has the bug** Colored Slimes

**Describe the bug**
Everything but the entity gets colored

**Screenshots**
![IMG_0103](https://github.com/BedrockTweaks/Files/assets/173629764/560c7640-b372-4618-b494-fa5616a32a42)

**Device (please complete the following information):**
 - OS: Xbox Series X/S
 - Minecraft Version: started appearing in 1.21.1

**Additional context**

**Comment by Chi-a11y** [comment]
it's true, i've tested it on both win and android

**Comment by Chi-a11y** [comment]
I've checked both on Win and Android, the sticky pistons, slimeball and slimeblock is there, turnss out the Slime entities png was missing

**Comment by SquatchHunter** [comment]
> I've checked both on Win and Android, the sticky pistons, slimeball and slimeblock is there, except for the slimes. Turns out the Slime entities .png file was missing

are you working on a PR to fix?

**Comment by Chi-a11y** [comment]
> > I've checked both on Win and Android, the sticky pistons, slimeball and slimeblock is there, except for the slimes. Turns out the Slime entities .png file was missing
> 
> are you working on a PR to fix?

Not at the moment, I'm going to pull a feature req so I'm not sure

**Comment by PAPISOP** [comment]
This issue is still not confirmed by DrAv so i don't think we can make a pr for this until DrAv confirms the issue

**Comment by PAPISOP** [comment]
Update: 
I just tried red colored slime and the slime entity is red color, maybe there might be a bug with a specific color of slime so can you specify what color slime you are using? @ParkR15MineR

**Comment by ParkR15MineR** [comment]
I was using purple slimes. Not sure if it was just purple but i saw on the discord it was fixed. I'll test it later when i have time, then let the discord know

**Comment by drav0011** [comment]
This was fixed with a site update which solved 
> Fixed a bug in the site which prevented files with the same name to be zipped in the file.

Slime block and entity had the same name so the entity was not being added
