### ISSUE TITLE
Smaller Utilities(Eating animations and totum not showing)

### ISSUE THREAD

**Issue by GlonicGDG** [BedrockTweaks/Files#111]
**Pack or combination of packs which has the bug*Smaller Utilities

**Describe the bug**
The eating animations is not showing and the Totum is invisable

**Screenshots**
![Screenshot_20240627_173844_Minecraft](https://github.com/BedrockTweaks/Files/assets/97624215/f2f67747-1153-44fe-9bde-b3b0cad7edb3)
![Screenshot_20240627_173821_Minecraft](https://github.com/BedrockTweaks/Files/assets/97624215/dced09a2-3745-49e2-808a-b65d0ea7ca09)
![Screenshot_20240627_173808_Minecraft](https://github.com/BedrockTweaks/Files/assets/97624215/5107a8ce-7587-4db4-a35c-5b69cde733b1)

**Device (please complete the following information):**
 - Windows 10, Android 21
 -  1.21.1

**Additional context**

**Comment by SquatchHunter** [comment]
reproducable, unsure what the cause is atm, investigating further

**Comment by drav0011** [comment]
Let's keep track of all issues with Smaller Utilities in #69
