### ISSUE TITLE
Raids Unavailable

### ISSUE THREAD

**Issue by BookablePilot2** [BedrockTweaks/Files#115]
I don't know what combination it is. Whenever drinking the new ominous bottles in a village it will "proc" the bad omen, but will never trigger the raid or the 30 sec cooldown.

 - Minecraft Version: [e.g 1.21.0]
 - All

**Comment by SquatchHunter** [comment]
pack list for the packs actively running? can you reproduce with a freshly download set (of the same packs)? is this confirmed to be our packs and not another pack you are running or vanilla behaviour?

**Comment by BookablePilot2** [comment]
Pack is running.
Can't download the current pack because Bedrock Tweaks addons down.
Confirmed to be your pack

**Comment by SquatchHunter** [comment]
if its an addon then this is probably closable, since all addons atm are not remade to 1.21 standards so bugs expected.

**Comment by TheAlienDoctor** [comment]
I know I'm late to this, but there's a lot of packs that use the player.json file that break the bad omen now. If you're using an old BT addon then that's probably the cause.

**Comment by drav0011** [comment]
Addons are not supported in 1.21, I suggest to remove the existing Bedrock Tweaks ones from your world
