### ISSUE TITLE
Smaller Utilities PACK

### ISSUE THREAD

**Issue by gemdruid** [BedrockTweaks/Files#116]
**Pack or combination of packs which has the bug**
Smaller Utilities

**Describe the bug**
Cod and Salmon both appear as their dropped item while still alive 

**Screenshots**

![minecraft](https://github.com/BedrockTweaks/Files/assets/174151089/7732c8b2-f1c9-4ed4-9758-fce86497b6dc)

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: [e.g 1.21.1]

**Comment by SquatchHunter** [comment]
this is BY FAR my favourite bug

**Comment by NSPC911** [comment]
this is way too funny lmao how does this bug even happen 🤣

**Comment by SquatchHunter** [comment]
it seems like the attachment file is pointed at the entity not the item somehow
