### ISSUE TITLE
[World of Color/Colorful Slime] All the packs

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#128]
**Pack or combination of packs which has the bug** All the packs in the category World of Color / Colorful Slime

**Describe the bug**
In vanilla tweaks, they also retexture the spawn egg texture for each color slime, but in bedrock tweaks, slime spawn eggs are not retextured.

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.1
 
 Vanilla Tweaks:
![Screenshot 2024-07-01 155831](https://github.com/BedrockTweaks/Files/assets/85175982/2cefd81c-7126-4c49-a6d4-fef31afbd3f9)

Bedrock Tweaks:
![Screenshot 2024-07-01 155806](https://github.com/BedrockTweaks/Files/assets/85175982/3289a171-edde-4000-8fde-2fec391b2527)

**Comment by PAPISOP** [comment]
Just letting anyone know that I am already working on this and when this issue is marked confirmed then I will make a pr

**Comment by NSPC911** [comment]
Yeah it was because each spawn egg now has its own specific calling name, and isn't part of the general spawn_egg index

**Comment by SquatchHunter** [comment]
I mean, we had methods to fix that with banner patterns so it could of been done first time around, the ongoing micro flattening is good though

**Comment by drav0011** [comment]
Thought I confirmed it, seems I did not, updated the status
