### ISSUE TITLE
[Quality of Life] Copper Powered Rails

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#135]
Add pack from vanilla tweaks

**Comment by drav0011** [comment]
> @drav0011 this isn't resource packs lol

Updated, thanks!

**Comment by SquatchHunter** [comment]
someone in the discord asked if this was done? or if it was being worked on? its not a large pack but a "good first issue" for some to tackle.

**Comment by PAPISOP** [comment]
> someone in the discord asked if this was done? or if it was being worked on? its not a large pack but a "good first issue" for some to tackle.

That's why I am not doing it, let someone else do it and also its milestone is marked as 5.2.0
