### ISSUE TITLE
Stairs, slabs to block PACK

### ISSUE THREAD

**Issue by CarrotMan78** [BedrockTweaks/Files#147]
Slabs, stairs to blocks

If you turn stairs or slabs to blocks it gives you 50% more, making infinite and can lead to infinite diamonds, emeralds and more

**Screenshots**

**Device (please complete the following information):
OS: All bedrock
 - Minecraft Version: 1.21

**Additional context**

**Comment by SquatchHunter** [comment]
Fixed in 5.1.0, waiting on DrAv to merge
