### ISSUE TITLE
[Peace and Quiet] Quieter Fire

### ISSUE THREAD

**Issue by drav0011** [BedrockTweaks/Files#154]
<div type='discussions-op-text'>

<sup>Originally posted by **BrianGLHF** July 12, 2024</sup>
> I'm not sure if campfires are counted as fire in quieter fire. would be great to have quieter campfires.
I appreciate the work. thank you!</div>

Checked Quieter Fire
It should be updated to contains all fire sounds same as in vanilla tweaks
Including but not limited to fire, player fire, flint and still, extinguish fire, campfires...

**Comment by NSPC911** [comment]
smh
