### ISSUE TITLE
[Beeralis] PACK

### ISSUE THREAD

**Issue by JCredjoker** [BedrockTweaks/Files#170]
**Beeralis pack**

**Describe the bug**
Hive is not capitalized

**Screenshots**
![Screenshot_20240719-104850_Minecraft](https://github.com/user-attachments/assets/10d5930f-23f2-45ee-bc7a-c21ca344ba4e)

**Device (please complete the following information):**
 - OS: Android 10
 - Minecraft Version: latest

**Additional context**

**Comment by SquatchHunter** [comment]
this is a "great first issue" moment
one translation file needs 1 letter changed - any takers.
