### ISSUE TITLE
[Utility] Hunger Preview

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#194]
**Pack or combination of packs which has the bug** Hunger Preview

**Describe the bug**
There are many errors in the translation el_GR.lang in texts folder (Greek Language) such as the placement of some text being inside the `(hunger bars)` and some texts are invalid text 

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.2

**Additional context**
I would suggest doing this translation completely from the start by using the vanilla file

**Comment by drav0011** [comment]
Could you provide screenshots of the issue?

**Comment by PAPISOP** [comment]
![Screenshot_20240723_002458_Minecraft](https://github.com/user-attachments/assets/9a6aceca-589e-4eaa-b5df-91d6e89f881c)

this is cooked salmon and you can see the things which is completely **WRONG** @drav0011

**Comment by SquatchHunter** [comment]
I assume its a issue with how Minecraft handles languages in the backend, it might be as simple as us using a different space on the glyph sheet?
that or whatever IDE you used originally to do the translations didnt like the characters

**Comment by PAPISOP** [comment]
I am self assigning myself to this issue, and I will make a pr when this issue is marked confirmed

**Comment by SquatchHunter** [comment]
this pack might be one that we do in waves as we have people translate, that way we can confirm that everything for each language looks OK
