### ISSUE TITLE
[Aesthetic/Zombie Varients] All (Except Zuri Varient)

### ISSUE THREAD

**Issue by ParkR15MineR** [BedrockTweaks/Files#199]
**All the selected zombies**

**Describe the bug**
Zombies appear to not have any texture

**Screenshots**
![01b5326a-54d7-450d-8cf7-bbefcf2006c8](https://github.com/user-attachments/assets/eddfbe29-03d2-4c3c-a1ca-b3751aabd098)

**Device (please complete the following information):**
 - OS: Xbox Series X/S
 - Minecraft Version: 1.21.2

**Additional context**
you can contact me on discord if you need any more questions answered

**Comment by ParkR15MineR** [comment]
Another picture for help
![33769119-0d62-4973-9f29-68793d9095a5](https://github.com/user-attachments/assets/6b4aa90d-2fb5-41c9-9572-da4b7bd7c77f)

**Comment by PAPISOP** [comment]
@ParkR15MineR This has been already fixed, update ur packs
