### ISSUE TITLE
[Unobtrusive] Lower Shield

### ISSUE THREAD

**Issue by Tbug20** [BedrockTweaks/Files#203]
**Pack or combination of packs which has the bug**
Lower Shield

**Describe the bug**
The front of the shield rather than the back shows in first person.

**Screenshots**
![image](https://github.com/user-attachments/assets/93db0a2d-127e-4a1d-8281-2b727d5ecdca)

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.3

**Comment by drav0011** [comment]
Seems this was an issue with lower mace which also made the shield reversed. should be fixed, if not reopen the issue
