### ISSUE TITLE
[Aesthetic] 3D Mace

### ISSUE THREAD

**Issue by Tbug20** [BedrockTweaks/Files#204]
**Pack or combination of packs which has the bug**
3D Mace

**Describe the bug**
The Mace is upside-down in first person.

**Screenshots**
![image](https://github.com/user-attachments/assets/cf06e250-dd8e-4742-ad77-d64f81a471b7)

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.3

**Comment by PAPISOP** [comment]
This has been fixed already so this bug report is invalid, update your pack @Tbug20
