### ISSUE TITLE
[Unobtrusive] Borderless Stained Glass

### ISSUE THREAD

**Issue by ParkR15MineR** [BedrockTweaks/Files#206]
**Borderless Stained Glass**

**Describe the bug**
Some of the texture for the glass has been switched

**Screenshots**
![image](https://github.com/user-attachments/assets/a5a7ce1d-b674-4f2b-9163-9bebd0c172b8)

**Device (please complete the following information):**
 - OS: Xbox Series X/S
 - Minecraft Version: 1.21.2

**Additional context**
Light Gray, Orange, Yellow, Lime, Green, Cyan, Blue, and Purple are the stained glass

**Comment by SquatchHunter** [comment]
can I just get a little clarification on this
what _exactly_ are you experiencing
are some of the regular glass being given the vanilla texture ? I dont quite understand what the issue is, from the photo I can tell but the text explaination is just a tad confusing (to me atleast)

**Comment by ParkR15MineR** [comment]
Ahh, I see. Some of the textures for the glass are using clean stained glass when they should be using borderless stained glass. I’ve separated the glass that the textures are different

**Comment by ParkR15MineR** [comment]
If you want, I could get a different picture

**Comment by PAPISOP** [comment]
Seems to be an issue with the backend

**Comment by drav0011** [comment]
This happens if you select both packs, clean stained glass and borderless stained glass, both packs are incompatible between them
