### ISSUE TITLE
[Retro] Old Wool Colors

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#210]
**Pack or combination of packs which has the bug** Old Wool Colors

**Describe the bug**
White wool is becoming bright red in color

**Screenshots**
Left is white wool and right is red wool
![image](https://github.com/user-attachments/assets/2fccdc77-7e99-4bf5-b7f5-88ea8e03acc5)

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.2

**Comment by PAPISOP** [comment]
I am self assigning myself to this issue, and I will make a pr when this issue is marked confirmed

**Comment by drav0011** [comment]
When does this happen? I cannot replicate it

**Comment by drav0011** [comment]
Update, tested the pack incorrectly seems the issue is happening, no idea why at first sight
