### ISSUE TITLE
[Retro] Old Planks

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#211]
**Pack or combination of packs which has the bug** Old Planks

**Describe the bug**
Beds are looking very weird

**Screenshots**
![image](https://github.com/user-attachments/assets/97f053db-9f8e-4179-955e-ad523d396f4c)

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.2

**Comment by SquatchHunter** [comment]
to clarify, this is a bug reported with the combination pack of old bed + old plank, not to be confused with the #212 issue which is just to update the pack

**Comment by PAPISOP** [comment]
> to clarify, this is a bug reported with the combination pack of old bed + old plank, not to be confused with the #212 issue which is just to update the pack
> 
> maybe track this or list it as a "task" for #71 to be closed.

there isn't any pack called old bed and no such combination exists for it, the pack itself has beds in it and it only changes the bed under plank texture to the old plank, nothing else
