### ISSUE TITLE
[Retro] Old Planks (update)

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#212]
**Pack or combination of packs which has the bug** Old Planks

**Describe the bug**
The pack is missing chest boats wood change, cherry plank texture change, and mangrove sign and boat texture change

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.2

**Comment by PAPISOP** [comment]
I am self assigning myself to this issue, and I will make a pr when this issue is marked confirmed

**Comment by drav0011** [comment]
Include pack decription change
