### ISSUE TITLE
[Peace & Quiet] Quieter Nether Portals

### ISSUE THREAD

**Issue by SquatchHunter** [BedrockTweaks/Files#221]
**Pack or combination of packs which has the bug**
Quieter Nether Portals

**Describe the bug**
Sounds still play at 100% rather then at 5%

**Device (please complete the following information):**
 - OS: All
 - Minecraft Version: 1.21.0+

**Additional context**
Possibly a underlying MC bug or upcoming change to sounds.json as non of the keys to adjust `portal.portal`, `portal.travel` or `portal.trigger` work from within sounds.json and have been modified in sound_definitions.json

**Comment by PAPISOP** [comment]
> **Pack or combination of packs which has the bug** Quieter Nether Portals
> 
> **Describe the bug** Sounds still play at 100% rather then at 5%
> 
> **Device (please complete the following information):**
> 
> * OS: All
> * Minecraft Version: 1.21.0+
> 
> **Additional context** Possibly a underlying MC bug or upcoming change to sounds.json as non of the keys to adjust `portal.portal`, `portal.travel` or `portal.trigger` work from within sounds.json and have been modified in sound_definitions.json

This is definitely a bug

**Comment by SquatchHunter** [comment]
this was closed in #197 to my knowledge
