### ISSUE TITLE
RETRO "OLD WOOL" PACK

### ISSUE THREAD

**Issue by xChopStix99** [BedrockTweaks/Files#252]
The "Old Wool Colors" pack under the "Retro" section is giving me a problem.

The white wool is very bright red for some reason, I'm not sure why. The same glitch goes for white carper, as well.

![Screenshot 2024-08-09 120712](https://github.com/user-attachments/assets/79d9bf68-0117-4950-9b6b-717d7edc5094))

![Screenshot 2024-08-09 120558](https://github.com/user-attachments/assets/9e01a0af-eae1-482c-8bc7-204bd4fd2a9f)

I'm playing Minecraft Bedrock on Windows 11, with v1.21.2

In case those screenshots are (for some reason) not working, they show what White Wool and White carpet look like in the inventory, and when placed. They're a very bright red. Not to be confused with the already existing texture for Red Wool. The White Wool has its own glitched color and texture.

**Comment by PAPISOP** [comment]
@xChopStix99 already addressed in #210 and fixed in #218 so wait for next hotfix update
