### ISSUE TITLE
[VARIATION] Multiple Variated Texture Problems

### ISSUE THREAD

**Issue by muttn** [BedrockTweaks/Files#255]
Bedrock Tweaks Variated Dirt, Brick, and Infested Cobblestone

I am not exactly sure if the Variated tweaks are causing this exact texture bug but I have been creating a Bedrock Tweaks pack for my XBOX and while creating the pack I came across some texture bugs where the texture was missing overall in some areas or the entire area, it has so far happened for me for Brick Slabs, Farmland, the Bottom of Grass, CobbleStone Walls, and Infested Stone Variants. As said before I am unsure if its exactly the Variants Tweaks but I was able to fix the missing infested stone and cobblestone wall texture by disabling cobblestone variations. I have linked the packs that all had texture bugs in one way or another

I made my pack on the most recent iOS and uploaded it to Mediafire where I downloaded it on my xbox from the mediafire link, currently using 1.21.2

![IMG_2641](https://github.com/user-attachments/assets/d53c37b0-3160-4b8f-adbe-55c15495e81f)

My Bedrock Tweaks Pack
https://www.mediafire.com/file/nwazk0k7c2xgaga/iiMatt.mcpack/file

**Comment by muttn** [comment]
My other packs attempting to fix these problems and single out which tweaks where causing the problems

https://www.mediafire.com/file/2ek5nc2xcjtvzew/MattTRG.mcpack/file
https://www.mediafire.com/file/9jprkkfhf095797/MattTRG2.mcpack/file
https://www.mediafire.com/file/k7wbs5rj6var8q5/MattTRG3.mcpack/file

**Comment by SquatchHunter** [comment]
> ⮞Some of my blocks do not have texture/have a black and purple texture, what is the problem?
You have not installed the pack properly. You have moved the pack to the resource packs folder instead of installing it. **DO NOT DRAG/MOVE THE RESOURCE PACKS, OR ADDONS, OR CRAFTING TWEAKS TO ANY FOLDER IN THE MINECRAFT DIRECTORY**

> That gives a lot of different issues: 
> - If packs are still compressed they take a lot more time to load.
> - If packs are still compressed some things do not even load.
> - Some packs (Addons and Crafting Tweaks) are a combination of Resource Packs and Behaviour Packs so they will not work if you move them.
> - You might move the pack to a different location instead of where it should go.
> - And more.
> Packs are made in a way when opening them they auto-install in the correct place, so use that.

Installing to Xbox may be subject to the same generic disclaimer above, cause as far as I am aware there is no reported issues with those packs on other platforms making me believe this may be an install issue with your current setup.

**Comment by muttn** [comment]
I do see your point, but after removing all Variations with my pack and installing it the same way I did before I have no texture issues at all, its only when there are variations on my pack where I have texture issues and everything else works flawlessly

**Comment by SquatchHunter** [comment]
I am going to put it down to the fact you have installed _something_ wrong still as I cannot replicate the issue you are describing on PC with any of the packs provided.

**Comment by drav0011** [comment]
As mentioned above some packs give no issues "installing" by copying the files to the respective folders but some more complex ones as variations, directional hoppers... do, I would suggest to try to rename the .mcpack to .zip and uncompressing them in the respective folders @muttn 

Cannot confirm if it will work or if it is possible as I do not have an Xbox console to try on
