### ISSUE TITLE
[Parity] Java map

### ISSUE THREAD

**Issue by IdotIcom** [BedrockTweaks/Files#257]
Trial explorer map texture not changed in "java map" pack

![Screenshot_2024-08-11-09-42-40-32](https://github.com/user-attachments/assets/f68833c4-3f20-4a3b-b2a6-6ab9360cabf9)

 - Android 10
 - Minecraft Version: 1.21.2.02

**Additional context**

**Comment by SquatchHunter** [comment]
java maps are so gross man

**Comment by SquatchHunter** [comment]
PR is in progress to fix, that will close this off as completed, till then I would leave it open
