### ISSUE TITLE
[CATEGORY] PACK the crown

### ISSUE THREAD

**Issue by Phinley461112** [BedrockTweaks/Files#258]
**Pack or combination of packs which has the bug**

**Describe the bug**

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. iOS 16, Windows 11, Android 21, Xbox Series]
 - Minecraft Version: [e.g 1.21.0]

**Additional context**
The crown texture isn't compatible with armour trims

**Comment by PAPISOP** [comment]
Please write a proper issue @Phinley461112

**Comment by SquatchHunter** [comment]
I assume they have had an issue with the Crown Helmet pack but thats a guess based on the title, I assume they have prematuraly hit submit and are unsure how to edit further

@Phinley461112 as Papi requested, can you provide some more context, either in the comments here, discord or edit your original post ("3 dots" > edit...)

**Comment by PAPISOP** [comment]
> I assume they have had an issue with the Crown Helmet pack but thats a guess based on the title, I assume they have prematuraly hit submit and are unsure how to edit further
> 
> @Phinley461112 as Papi requested, can you provide some more context, either in the comments here, discord or edit your original post ("3 dots" > edit...) otherwise this issue will be closed as invalid

Basically the trim is not working on the golden crown helmet, I will make a new issue describing it in detail soon
