### ISSUE TITLE
[CATEGORY] Pack

### ISSUE THREAD

**Issue by Uneasy1600** [BedrockTweaks/Files#262]
I want to make this breif but the “Pixelated Minecraft logo” on the retro on mobile is too big and low so it looks weird and ugly. 

PS. Other than that, I LOVE THIS WEBSITE its awesome! My favorite addon!

**Comment by PAPISOP** [comment]
> I want to make this breif but the “Pixelated Minecraft logo” on the retro on mobile is too big and low so it looks weird and ugly.
> 
> PS. Other than that, I LOVE THIS WEBSITE its awesome! My favorite addon!

That's why it's called "pixelated" for a reason

**Comment by SquatchHunter** [comment]
pixelated should still be a decent aspect resolution so it doesnt look "weird and ugly"

@Uneasy1600 send a screen shot and explain a bit more by your definition of ugly :)
