### ISSUE TITLE
[All] Backend changes

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#266]
Update all the RPs to use latest format for `blocks.json` and `terrain_texture.json`

Use `"1.21.40"` format version instead of `[1, 1, 0]` in `blocks.json` for future compatibility, due to this, we need to also update the version in `packs.json` to be 1.21.40

This is for better compatibility for newer minecraft versions as packs like Double Slab Fix dont break again

We should do it after 1.21.40 release as of right now, bedrock samples for 1.21.20 is still using outdated/old way of doing blocks.json which doesn't include newer additions which is fixed in 1.21.30 preview bedrock samples and a mojang dev has confirmed that flattening will be finished in 1.21.40 so we have to wait for that

**Comment by SquatchHunter** [comment]
name suggestion:
chore(files): blocks.json updates

**Comment by drav0011** [comment]
Scheduling for 1.22 unless mayor breaking changes happen to (try to) ensure compatibility with all the 1.21 versions
