### ISSUE TITLE
[CATEGORY] PACK

### ISSUE THREAD

**Issue by GroundGrub** [BedrockTweaks/Files#267]
The beds texture is messed up

The beds texture is messed up and scrambled leaving invisible segments

 - Minecraft Version: 1.21.20

**Comment by PAPISOP** [comment]
Which pack? @GroundGrub

**Comment by SquatchHunter** [comment]
I assume Retro/Old_Beds?

**Comment by PAPISOP** [comment]
Bed textures are only changed by Old Planks pack which is already fixed in 5.1.7, so this bug report is fixed and should be closed

**Comment by SquatchHunter** [comment]
time of creation, 5.1.7 wasnt out
plus no response from issue maker, assume invalid and close
