### ISSUE TITLE
[Resource Packs] Glass tweaks don't work together

### ISSUE THREAD

**Issue by Mat-Coughin** [BedrockTweaks/Files#277]
**Pack or combination of packs which has the bug**
Borderless Glass and Clean Glass

**Describe the bug**
These packs seem to be mutually exclusive 

**Screenshots**
N/A

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.0

**Additional context**
When loaded together, I will get random colors of stained glass that will either be Borderless or Clean

**Comment by PAPISOP** [comment]
Those two packs are incompatible with each one, so this is Wont Fix scenario

**Comment by SquatchHunter** [comment]
Borderless + Clean Glass would render it invisable.
there were plans to put a warning for incompatible packs on the site, but it hasnt been done yet, maybe a packs.json edit would be in order using the "new" system DrAv implemented

**Comment by drav0011** [comment]
Incompatibility warnings will come in a future update
