### ISSUE TITLE
I was going to go download some mods from the website, but when I click download, it loads, and just stops loading. No Google download popup, no Apple redirect, nothing. Just stops downloading.

### ISSUE THREAD

**Issue by IsBlankAnOption** [BedrockTweaks/Files#279]
No screenshots are available.

Model: iPad Air (4th Generation)
iOS version: 17.6.1

Looked into my files, and nothing recent was downloaded. Also checked Minecraft, and nothing was downloaded onto my resource packs or behavior packs.

**Comment by PAPISOP** [comment]
Use Official Chrome to download the pack as there's a bug in which download might not work in other browsers

**Comment by PAPISOP** [comment]
Tbh @drav0011 should fix this bug as he is the one who handles the website

**Comment by SquatchHunter** [comment]
afaik this has been a bug due to the website host and not exactly issues with DrAv's code
atleast that was the case back on the old google domain / site, idk about this new rework

**Comment by IsBlankAnOption** [comment]
Thank you so much for solving the problem! It works now!
