### ISSUE TITLE
[Quality of Life] Universal Dyeing

### ISSUE THREAD

**Issue by PAPISOP** [BedrockTweaks/Files#311]
**Pack or combination of packs which has the bug** Universal Dyeing

**Describe the bug**
It doesn't work at all, and also this one is I am not sure but it should include candles and glazed terracotta too as it is how it is done in Vanilla Tweaks

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.22

**Comment by SquatchHunter** [comment]
I believe I identified the issue for this a long time ago
the crafting priority is set to -1 which basically breaks it for anyone not manually doing it, have you tested if it works by manually moving the items to the grid.

**Comment by PAPISOP** [comment]
> I believe I identified the issue for this a long time ago the crafting priority is set to -1 which basically breaks it for anyone not manually doing it, have you tested if it works by manually moving the items to the grid.

seems like an issue with flattening, I think flattening broke it

**Comment by SquatchHunter** [comment]
possible

**Comment by SquatchHunter** [comment]
![image](https://github.com/user-attachments/assets/9a97c3e7-12ad-410a-a7fe-5a359a12751f)
fresh downloaded pack appears to be working as expected.

**Comment by PAPISOP** [comment]
Just checked, and it's working actually working (mb), so closing this issue
