### ISSUE TITLE
[Variations] Variated Terracotta

### ISSUE THREAD

**Issue by waffleeiron** [BedrockTweaks/Files#316]
**Variated Terracotta**

**Describe the bug**
Regular Terracotta isn't variated, stained terracotta however is

**Device:**
 - OS: Android 14
 - Minecraft Version: 1.21.3

**Additional context**
Tried several other terms to replace "hardened_clay" ID in terrain_texture.json with

**Comment by PAPISOP** [comment]
It's working fine, `stained_clay` is still the id for normal terracotta and it has not been updated (or maybe never) to `terracotta` @waffleeiron 
![image](https://github.com/user-attachments/assets/e566b2f1-0421-4cb5-9e67-5884c17d33c9)
