### ISSUE TITLE
[Combination] Coloured Slime + Sticky Piston Sides

### ISSUE THREAD

**Issue by SquatchHunter** [BedrockTweaks/Files#319]
Coloured Slime + Sticky Piston Sides

**Describe the bug**
Sticky Piston Sides overrides Coloured slime and renders the piston, broken, the wrong colour of vanilla when it shouldnt be

**Device (please complete the following information):**
 - OS: All
 - Minecraft Version: 1.21+

**Comment by PAPISOP** [comment]
This is already fixed by introducing priority to the packs
