### ISSUE TITLE
GUI - villager trade helper

### ISSUE THREAD

**Issue by JustAJack3t** [BedrockTweaks/Files#358]
Also i found a bug whilst making the villager ui, if you hover over an item, you can see the stack count through the item info. Its an easy fix, just changing the layer from the item info overlay from 11 to 12 does the trick. 😄
![Schermafbeelding 2024-10-10 201508](https://github.com/user-attachments/assets/21e6688f-f408-42bc-ba6c-8875c4049bf8)

**Comment by PAPISOP** [comment]
Cant reproduce, please provide an image to understand what you are actually saying @codermetlol

**Comment by PAPISOP** [comment]
Update:
Can reproduce after seeing the image
