### ISSUE TITLE
[GUI/No How To Play] Smithing Table

### ISSUE THREAD

**Issue by Azer-7896** [BedrockTweaks/Files#86]
**No How To Play**

**The bug:**
Smithing table still has how to play button after activating the pack when it should remove that button.
![16AA908F-9DBB-4178-A240-588261E08107](https://github.com/BedrockTweaks/Files/assets/173142587/3b209606-0573-48b5-8169-1bd9ddc1d8e4)

**Device:**
 - iOS 15.8.2
 - Minecraft Version: 1.21.0

**Additional context:**
Issue started since smithing table got a new purpose and a new user interface.

**Comment by NSPC911** [comment]
Likely because the smithing table got the update for the armor trims, so it definitely must have messed up some stuff in the smithing_screen.json
