### ISSUE TITLE
[Aesthetic] HD Shield Banner Patterns

### ISSUE THREAD

**Issue by drav0011** [BedrockTweaks/Files#92]
### Discussed in https://github.com/BedrockTweaks/Files/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **NSPC911** June 19, 2024</sup>
Interestingly was not in [issues](https://github.com/BedrockTweaks/Files/issues) even though it is definitely a possible pack but there is no trace of it in [packs.json](https://github.com/BedrockTweaks/Files/blob/devel/resource_packs/packs.json).</div>

Add missing pack from Vanilla Tweaks

**Comment by SquatchHunter** [comment]
someone in the discord has already made this and given prior permission to post
https://discord.com/channels/567364180857061437/1231437051451277382

**Comment by NSPC911** [comment]
> someone in the discord has already made this and given prior permission to post
> https://discord.com/channels/567364180857061437/1231437051451277382
> 

hasnt been updated for the new banners

**Comment by SquatchHunter** [comment]
that was unforeseeable at the time they made the pack, but a bulk of the work is done.

**Comment by drav0011** [comment]
This is the correct link
https://discord.com/channels/567364180857061437/1207550459087425537
Also would prefer if them made the PR rather than have 3rd parties upload it. 
A new work from 0 would also be good.
This is to avoid issues in the future with packs permissions
